version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: "hgcab/oauth-server:${APP_VERSION}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_AUTH_URI=${DB_AUTH_URI}
    volumes:
      - .:/home/node/app
    ports:
      - '6001:6001'
    command: npm start
