version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    image: "$APP_NAME:$APP_VERSION"
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - .:/home/node/app
    ports:
      - '6001:6001'
    command: npm start
